const projectdata = [
    {
        id:1,
        projectName :"Guess My Number",
        aboutProject: "In this game We can guess the number if the number is not matched then the notfier notify you the number is not match.if number is matched the background color is changed and score and highscore will be change and life is also decrease.",
        FrameWork: "React JS",
        ProgrammingLang: "Javascript",
        webLang: "HTML",
        styling:"CSS",
    },
    {
        id:2,
        projectName :"Random Quote Generator",
        aboutProject: "In this we can generate the random motivational quotes and i am added the speech synthesis system which helps to speak the quotes.",
        FrameWork: "React Js",
        ProgrammingLang: "Javascript",
        webLang: "HTML",
        styling:"CSS",
    },
    {
        id:3,
        projectName :"Expense Tracker",
        aboutProject: "This app is made from using HTML, CSS ,JAVASCRIPT and this app to help to save your income and expenses and according to income and expense it has to update your budget balance .",
        FrameWork: "React Js",
        ProgrammingLang: "Javascript",
        webLang: "HTML",
        styling:"CSS",
    },
    {
        id:4,
        projectName :"Expense Tracker",
        aboutProject: "This app is made from using HTML, CSS ,JAVASCRIPT and this app to help to save your income and expenses and according to income and expense it has to update your budget balance .",
        FrameWork: "React Js",
        ProgrammingLang: "Javascript",
        webLang: "HTML",
        styling:"CSS",
    },
    {
        id:5,
        projectName :"Expense Tracker",
        aboutProject: "This app is made from using HTML, CSS ,JAVASCRIPT and this app to help to save your income and expenses and according to income and expense it has to update your budget balance .",
        FrameWork: "React Js",
        ProgrammingLang: "Javascript",
        webLang: "HTML",
        styling:"CSS",
    },
    {
        id:5,
        projectName :"Expense Tracker",
        aboutProject: "This app is made from using HTML, CSS ,JAVASCRIPT and this app to help to save your income and expenses and according to income and expense it has to update your budget balance .",
        FrameWork: "React Js",
        ProgrammingLang: "Javascript",
        webLang: "HTML",
        styling:"CSS",
    },
]